/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as LoginRouteImport } from './pages/login'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AppSimulateRouteImport } from './pages/_app/simulate'
import { Route as AppIntegrationsRouteImport } from './pages/_app/integrations'
import { Route as AppFlowBuilderRouteImport } from './pages/_app/flow-builder'
import { Route as AppChatBuilderRouteImport } from './pages/_app/chat-builder'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppSimulateRoute = AppSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppFlowBuilderRoute = AppFlowBuilderRouteImport.update({
  id: '/flow-builder',
  path: '/flow-builder',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppChatBuilderRoute = AppChatBuilderRouteImport.update({
  id: '/chat-builder',
  path: '/chat-builder',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/chat-builder': typeof AppChatBuilderRoute
  '/flow-builder': typeof AppFlowBuilderRoute
  '/integrations': typeof AppIntegrationsRoute
  '/simulate': typeof AppSimulateRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/chat-builder': typeof AppChatBuilderRoute
  '/flow-builder': typeof AppFlowBuilderRoute
  '/integrations': typeof AppIntegrationsRoute
  '/simulate': typeof AppSimulateRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/chat-builder': typeof AppChatBuilderRoute
  '/_app/flow-builder': typeof AppFlowBuilderRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/simulate': typeof AppSimulateRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chat-builder'
    | '/flow-builder'
    | '/integrations'
    | '/simulate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/chat-builder'
    | '/flow-builder'
    | '/integrations'
    | '/simulate'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/chat-builder'
    | '/_app/flow-builder'
    | '/_app/integrations'
    | '/_app/simulate'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/simulate': {
      id: '/_app/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof AppSimulateRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/flow-builder': {
      id: '/_app/flow-builder'
      path: '/flow-builder'
      fullPath: '/flow-builder'
      preLoaderRoute: typeof AppFlowBuilderRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/chat-builder': {
      id: '/_app/chat-builder'
      path: '/chat-builder'
      fullPath: '/chat-builder'
      preLoaderRoute: typeof AppChatBuilderRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppChatBuilderRoute: typeof AppChatBuilderRoute
  AppFlowBuilderRoute: typeof AppFlowBuilderRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppSimulateRoute: typeof AppSimulateRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppChatBuilderRoute: AppChatBuilderRoute,
  AppFlowBuilderRoute: AppFlowBuilderRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppSimulateRoute: AppSimulateRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
